name: telegram_bot_crashlytics
description: "A Flutter package that automatically sends bad HTTP responses from API requests directly to your Telegram group for easier monitoring and debugging."
version: 1.2.3
homepage: "https://github.com/JaysonKhan/telegram_bot_crashlytics.git"
repository: "https://github.com/JaysonKhan/telegram_bot_crashlytics"
license: "MIT"

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  http: ^1.2.2
  logging: ^1.3.0
  device_info_plus: ^11.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0