name: telegram_bot_crashlytics
description: "A new Flutter package which xullas apidan kelgan bad responcelani telegram guruhingizga tashlab beradi"
version: 1.0.0
homepage: "https://github.com/JaysonKhan/telegram_bot_crashlytics.git"
repository: "https://github.com/JaysonKhan/telegram_bot_crashlytics"
license: "MIT"

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  http: ^1.2.2
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0